id: 97b57f9d-b55e-465c-96b3-4adb5883fe9c

# Name of the quickstart (required)
slug: winservices

# Title of the quickstart
title: Windows Services

# Description of the quickstart
description: |
  ## Windows Services

  New Relic's Windows services integration collects data about the services running on your Microsoft Windows hosts and sends it to our platform. 
  You can check the state and start mode of each service, find out which hosts are running a service, set up alerts for services, and more.

  Our integration is bundled with the Windows infrastructure agent. If you're monitoring Windows hosts on New Relic, you only need to enable the integration to get Windows services data into our platform.

summary: |
  New Relic's Windows services integration collects data about the services running on your Microsoft Windows hosts
# Support level
level: New Relic

# Design
icon: logo.svg
website: https://www.microsoft.com/en-us/windows

keywords:
  - windows
  - microsoft
  - service
  - os
  - operating system

# Authors of the quickstart (required)
authors:
  - New Relic

documentation:
  - name: Windows Services monitoring integration
    description: |
      New Relic's Windows services integration collects data about the services running on your Microsoft Windows hosts and sends it to our platform. 
    url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/windows-services-integration/

installPlans:
  - winservices-integration-docs

dashboards:
  - winservices
